var app = new Vue (
  {
    el : '#app',
    data :{
      avadaLinks:[
        {
          title:'home',
          link:'#'
        },
        {
          title:'raters',
          link:'#'
        },
        {
          title:'testimonials',
          link:'#'
        },
        {
          title:'FAQ',
          link:'#'
        },
        {
          title:'blog',
          link:'#'
        },
        {
          title:'contact',
          link:'#'
        },
        {
          title:'free quote',
          link:'#'
        }
      ],
      recentPost:[
        {
          title:'',
          link:'#'
        },
        {
          title:'',
          link:'#'
        },
        {
          title:'',
          link:'#'
        },
        {
          title:'',
          link:'#'
        },
        {
          title:'',
          link:'#'
        },
      ]
    }
  }
)
